# Generated by Django 5.1.13 on 2026-06-19 12:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=30)),
                ("attempts", models.IntegerField(default=0)),
                ("error", models.TextField(default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("queue_order", models.IntegerField(db_index=True, default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ingestion_jobs", to="documents.documentreference")),
            ],
            options={
                "db_table": "ingestion_jobs",
            },
        ),
        migrations.CreateModel(
            name="IngestionStepAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("step_type", models.CharField(choices=[("extract", "Extract"), ("ocr", "OCR"), ("chunk", "Chunk"), ("summarize", "Summarize"), ("hypothetical_questions", "Hypothetical Questions"), ("embed_text", "Embed Text"), ("embed_multimodal", "Embed Multimodal"), ("index", "Index")], max_length=50)),
                ("attempt_number", models.IntegerField(default=1)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("skipped", "Skipped")], default="queued", max_length=30)),
                ("error", models.TextField(blank=True, default="")),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="step_attempts", to="ingestion.ingestionjob")),
            ],
            options={
                "db_table": "ingestion_step_attempts",
            },
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["status", "created_at"], name="ingestion_j_status_2139c5_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["document_reference", "-created_at"], name="ingestion_j_documen_71b30f_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionstepattempt",
            index=models.Index(fields=["job", "step_type"], name="ingestion_s_job_id_e3ad2c_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionstepattempt",
            index=models.Index(fields=["job", "status"], name="ingestion_s_job_id_08b4f6_idx"),
        ),
        migrations.AddConstraint(
            model_name="ingestionstepattempt",
            constraint=models.UniqueConstraint(fields=("job", "step_type", "attempt_number"), name="unique_job_step_attempt"),
        ),
    ]
