# Generated by Django 5.1.13 on 2026-06-19 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('observability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_grants',
            },
        ),
        migrations.CreateModel(
            name='ChatShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_shares',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=30)),
                ('content', models.TextField(default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=30)),
                ('tool_invocations', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_messages', to='chat.message')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_content', models.TextField(default='')),
                ('new_content', models.TextField(default='')),
                ('previous_metadata', models.JSONField(blank=True, default=dict)),
                ('new_metadata', models.JSONField(blank=True, default=dict)),
                ('superseded_message_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_edits', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='chat.message')),
            ],
            options={
                'db_table': 'message_edits',
            },
        ),
        migrations.CreateModel(
            name='ChatBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='main', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='chat.chat')),
                ('base_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_from', to='chat.message')),
                ('head_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_to', to='chat.message')),
            ],
            options={
                'db_table': 'chat_branches',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='documents.documentreference')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_objects', to='chat.message')),
            ],
            options={
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageDelta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('delta_type', models.CharField(choices=[('text', 'Text'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('error', 'Error'), ('done', 'Done')], default='text', max_length=30)),
                ('content', models.TextField(default='')),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='chat.message')),
            ],
            options={
                'db_table': 'message_deltas',
            },
        ),
        migrations.CreateModel(
            name='TurnRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('worker_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_runs', to='chat.chatbranch')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_runs', to='chat.chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_runs', to='chat.message')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_runs', to='observability.executiontrace')),
            ],
            options={
                'db_table': 'turn_runs',
            },
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('event_type', models.CharField(choices=[('progress', 'Progress'), ('text_delta', 'Text Delta'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('error', 'Error'), ('done', 'Done')], default='progress', max_length=30)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.turnrun')),
            ],
            options={
                'db_table': 'turn_events',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_upvoted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chat.chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'archived', '-updated_at'], name='chats_user_id_5bbd81_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at'], name='chats_user_id_5516a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['archived'], name='chats_archive_ca9248_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('user', 'path'), name='unique_user_chat_path'),
        ),
        migrations.AddIndex(
            model_name='chatgrant',
            index=models.Index(fields=['chat'], name='chat_grants_chat_id_76407f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgrant',
            index=models.Index(fields=['user'], name='chat_grants_user_id_de7a41_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatgrant',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='unique_chat_grant'),
        ),
        migrations.AddIndex(
            model_name='chatshare',
            index=models.Index(fields=['chat', 'revoked'], name='chat_shares_chat_id_8e25ef_idx'),
        ),
        migrations.AddIndex(
            model_name='chatshare',
            index=models.Index(fields=['user', '-created_at'], name='chat_shares_user_id_93544c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatshare',
            index=models.Index(fields=['token'], name='chat_shares_token_a325ce_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='messages_chat_id_ec31ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'role', '-created_at'], name='messages_chat_id_3d1280_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'status', '-created_at'], name='messages_chat_id_df4901_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author'], name='messages_author__93b7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='messageedit',
            index=models.Index(fields=['message', '-created_at'], name='message_edi_message_e057a3_idx'),
        ),
        migrations.AddIndex(
            model_name='messageedit',
            index=models.Index(fields=['editor', '-created_at'], name='message_edi_editor__07a020_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbranch',
            index=models.Index(fields=['chat', 'is_active'], name='chat_branch_chat_id_091db8_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbranch',
            constraint=models.UniqueConstraint(fields=('chat', 'name'), name='unique_chat_branch_name'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='message_att_message_2a1fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['document_reference'], name='message_att_documen_728d12_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelta',
            index=models.Index(fields=['message', 'sequence'], name='message_del_message_4b72b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedelta',
            constraint=models.UniqueConstraint(fields=('message', 'sequence'), name='unique_message_delta_sequence'),
        ),
        migrations.AddIndex(
            model_name='turnrun',
            index=models.Index(fields=['status', 'created_at'], name='turn_runs_status_31326c_idx'),
        ),
        migrations.AddIndex(
            model_name='turnrun',
            index=models.Index(fields=['chat', '-created_at'], name='turn_runs_chat_id_a3d0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='turnrun',
            index=models.Index(fields=['branch', 'status'], name='turn_runs_branch__2326d1_idx'),
        ),
        migrations.AddIndex(
            model_name='turnrun',
            index=models.Index(fields=['worker_id'], name='turn_runs_worker__e74ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='turnevent',
            index=models.Index(fields=['turn_run', 'sequence'], name='turn_events_turn_ru_2fdd88_idx'),
        ),
        migrations.AddIndex(
            model_name='turnevent',
            index=models.Index(fields=['turn_run', 'event_type'], name='turn_events_turn_ru_a17c08_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnevent',
            constraint=models.UniqueConstraint(fields=('turn_run', 'sequence'), name='unique_turn_event_sequence'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['chat'], name='votes_chat_id_67c5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['message'], name='votes_message_74d6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_user_message_vote'),
        ),
    ]
