# Generated by Django 5.1.2 on 2026-05-25 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('llm', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='tool_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='tools.toolcall'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['tool_call'], name='token_usage_tool_ca_9e5488_idx'),
        ),
    ]
