# Generated by Django 5.1.13 on 2026-06-19 12:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("mime_type", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("object_key", models.CharField(blank=True, default="", max_length=1024)),
                ("storage_status", models.CharField(choices=[("pending", "Pending"), ("stored", "Stored"), ("failed", "Failed")], default="pending", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_blobs",
                "indexes": [models.Index(fields=["content_hash"], name="content_blo_content_961f12_idx"), models.Index(fields=["storage_status"], name="content_blo_storage_3c5b49_idx")],
            },
        ),
        migrations.CreateModel(
            name="ArtifactRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pipeline_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("pipeline_version", models.CharField(default="1", max_length=50)),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("processing_status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("ready", "Ready"), ("failed", "Failed")], default="pending", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blob", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifact_revisions", to="documents.contentblob")),
            ],
            options={
                "db_table": "artifact_revisions",
            },
        ),
        migrations.CreateModel(
            name="DocumentReference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("kind", models.CharField(choices=[("knowledge", "Knowledge"), ("chat_attachment", "Chat Attachment")], max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artifact_revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_references", to="documents.artifactrevision")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_references", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "document_references",
            },
        ),
        migrations.CreateModel(
            name="DocumentGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("viewer", "Viewer"), ("editor", "Editor")], max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_grants", to=settings.AUTH_USER_MODEL)),
                ("document_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="documents.documentreference")),
            ],
            options={
                "db_table": "document_grants",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingSet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=255)),
                ("model_version", models.CharField(default="", max_length=50)),
                ("embedding_type", models.CharField(choices=[("text", "Text"), ("multimodal", "Multimodal")], max_length=30)),
                ("dimensions", models.IntegerField(default=0)),
                ("milvus_collection", models.CharField(max_length=255)),
                ("milvus_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("artifact_revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="embedding_sets", to="documents.artifactrevision")),
            ],
            options={
                "db_table": "embedding_sets",
            },
        ),
        migrations.AddIndex(
            model_name="artifactrevision",
            index=models.Index(fields=["blob", "processing_status"], name="artifact_re_blob_id_a17d10_idx"),
        ),
        migrations.AddIndex(
            model_name="artifactrevision",
            index=models.Index(fields=["pipeline_fingerprint"], name="artifact_re_pipelin_79a4b0_idx"),
        ),
        migrations.AddConstraint(
            model_name="artifactrevision",
            constraint=models.UniqueConstraint(fields=("blob", "pipeline_fingerprint"), name="unique_blob_pipeline"),
        ),
        migrations.AddIndex(
            model_name="documentreference",
            index=models.Index(fields=["owner", "kind", "-created_at"], name="document_re_owner_i_e2b035_idx"),
        ),
        migrations.AddIndex(
            model_name="documentreference",
            index=models.Index(fields=["owner", "-updated_at"], name="document_re_owner_i_7cb7fd_idx"),
        ),
        migrations.AddIndex(
            model_name="documentreference",
            index=models.Index(fields=["artifact_revision"], name="document_re_artifac_77987f_idx"),
        ),
        migrations.AddIndex(
            model_name="documentgrant",
            index=models.Index(fields=["document_reference"], name="document_gr_documen_cbcea5_idx"),
        ),
        migrations.AddIndex(
            model_name="documentgrant",
            index=models.Index(fields=["user"], name="document_gr_user_id_063ee7_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentgrant",
            constraint=models.UniqueConstraint(fields=("document_reference", "user"), name="unique_document_grant"),
        ),
        migrations.AddIndex(
            model_name="embeddingset",
            index=models.Index(fields=["artifact_revision"], name="embedding_s_artifac_0fe01f_idx"),
        ),
        migrations.AddIndex(
            model_name="embeddingset",
            index=models.Index(fields=["model_name", "embedding_type"], name="embedding_s_model_n_c4bee5_idx"),
        ),
        migrations.AddConstraint(
            model_name="embeddingset",
            constraint=models.UniqueConstraint(fields=("artifact_revision", "model_name", "embedding_type"), name="unique_revision_embedding"),
        ),
    ]
