# Generated by Django 5.1.2 on 2026-05-25 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(max_length=255)),
                ('file', models.CharField(blank=True, max_length=1024, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('extracted_text', models.TextField(default='')),
                ('analysis_summary', models.TextField(default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('page', 'Page'), ('table', 'Table'), ('audio', 'Audio'), ('video_frame', 'Video Frame')], max_length=30)),
                ('file', models.CharField(blank=True, max_length=1024, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(default='')),
                ('analysis', models.TextField(default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='knowledge.document')),
            ],
            options={
                'db_table': 'document_assets',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('token_count', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='knowledge.documentasset')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('folder', 'Folder'), ('manual', 'Manual'), ('api', 'API')], default='upload', max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('global', 'Global')], default='private', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_sources',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource'),
        ),
        migrations.CreateModel(
            name='RetrievalRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('query_embedding', models.JSONField(blank=True, null=True)),
                ('strategy', models.CharField(choices=[('vector', 'Vector'), ('text', 'Text'), ('hybrid', 'Hybrid')], default='hybrid', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_runs', to='chat.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_runs', to='chat.message')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_runs', to='tools.toolcall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retrieval_runs',
            },
        ),
        migrations.CreateModel(
            name='RetrievalHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('score', models.FloatField(default=0)),
                ('source_title', models.CharField(max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_hits', to='knowledge.documentchunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='knowledge.retrievalrun')),
            ],
            options={
                'db_table': 'retrieval_hits',
            },
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['document', 'asset_type'], name='document_as_documen_30abe8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['document', 'page_number'], name='document_as_documen_1e2325_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['content_hash'], name='document_ch_content_789e15_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['owner', 'source_type'], name='knowledge_s_owner_i_da0491_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['visibility'], name='knowledge_s_visibil_98d15f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='documents_owner_i_9f8226_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'status'], name='documents_source__25f803_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256'], name='documents_sha256_88e6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalrun',
            index=models.Index(fields=['user', '-created_at'], name='retrieval_r_user_id_9c54dd_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalrun',
            index=models.Index(fields=['chat', '-created_at'], name='retrieval_r_chat_id_dec063_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalrun',
            index=models.Index(fields=['tool_call'], name='retrieval_r_tool_ca_1bac88_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalhit',
            index=models.Index(fields=['run', 'rank'], name='retrieval_h_run_id_9fd414_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalhit',
            index=models.Index(fields=['chunk'], name='retrieval_h_chunk_i_000f4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.UniqueConstraint(fields=('run', 'chunk'), name='unique_retrieval_hit'),
        ),
    ]
