# Generated by Django 5.1.2 on 2026-05-25 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('auto_save', models.BooleanField(default=True)),
                ('auto_save_filter', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=30)),
                ('allow_tool_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_settings',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('importance', models.IntegerField(default=1)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memories',
                'indexes': [models.Index(fields=['user', 'importance', '-last_used_at'], name='memories_user_id_bf283f_idx'), models.Index(fields=['user', '-updated_at'], name='memories_user_id_36d6ec_idx')],
            },
        ),
    ]
