# Generated by Django 5.1.13 on 2026-06-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='embedding',
        ),
    ]
