# Generated by Django 5.1.13 on 2026-06-19 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_type', models.CharField(choices=[('ingestion', 'Ingestion'), ('turn', 'Turn'), ('retrieval', 'Retrieval')], max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'execution_traces',
                'indexes': [models.Index(fields=['trace_type', '-started_at'], name='execution_t_trace_t_4f526f_idx'), models.Index(fields=['status'], name='execution_t_status_dd494a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('lora_adapter', models.CharField(blank=True, default='', max_length=255)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('time_to_first_token_ms', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=30)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parent_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_spans', to='observability.executionspan')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='observability.executiontrace')),
            ],
            options={
                'db_table': 'execution_spans',
                'indexes': [models.Index(fields=['trace', 'operation'], name='execution_s_trace_i_c6fed3_idx'), models.Index(fields=['trace', 'parent_span'], name='execution_s_trace_i_c5f186_idx'), models.Index(fields=['trace', '-started_at'], name='execution_s_trace_i_818241_idx'), models.Index(fields=['operation', 'status'], name='execution_s_operati_f56e05_idx')],
            },
        ),
    ]
