# Generated by Django 5.1.2 on 2026-05-25 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCompaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('facts', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('token_count', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compactions', to='chat.chat')),
                ('from_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compactions_from', to='chat.message')),
                ('to_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compactions_to', to='chat.message')),
            ],
            options={
                'db_table': 'chat_compactions',
                'indexes': [models.Index(fields=['chat', '-created_at'], name='chat_compac_chat_id_44f98f_idx'), models.Index(fields=['chat', 'from_message', 'to_message'], name='chat_compac_chat_id_c478a4_idx')],
            },
        ),
    ]
