# Generated by Django 5.1.13 on 2026-06-24 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_filename', models.CharField(blank=True, default='', max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('ocr_mode', models.CharField(blank=True, default='none', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=50)),
                ('file', models.CharField(blank=True, default='', max_length=1024)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('analysis', models.TextField(blank=True, default='')),
                ('source_index', models.IntegerField(default=0)),
                ('derived_index', models.IntegerField(default=0)),
                ('object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('ocr_backend', models.CharField(default='none', max_length=50)),
                ('ocr_status', models.CharField(default='skipped', max_length=30)),
                ('preprocessing', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'document_assets',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('visibility', models.CharField(default='private', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_sources',
                'indexes': [models.Index(fields=['source_type', 'name'], name='knowledge_s_source__55c865_idx')],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='knowledge.documentasset')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['document', 'asset_type'], name='document_as_documen_30abe8_idx'),
        ),
    ]
