# Generated by Django 5.1.13 on 2026-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentasset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='documentasset',
            name='object_key',
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
