# Generated by Django 5.1.13 on 2026-06-11 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('knowledge', '0002_remove_documentchunk_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagSearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_query', models.TextField()),
                ('enhanced_queries', models.JSONField(blank=True, default=list)),
                ('hyde_docs', models.JSONField(blank=True, default=list)),
                ('sub_queries', models.JSONField(blank=True, default=list)),
                ('stepback_question', models.TextField(blank=True, default='')),
                ('retrieval_mode', models.CharField(default='hybrid', max_length=30)),
                ('use_reranker', models.BooleanField(default=True)),
                ('hierarchical', models.BooleanField(default=True)),
                ('total_results', models.IntegerField(default=0)),
                ('result_sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_search_logs', to='chat.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_search_logs', to='chat.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Search Log',
                'verbose_name_plural': 'RAG Search Logs',
                'db_table': 'rag_search_logs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='rag_search__user_id_9fc374_idx'), models.Index(fields=['chat', '-created_at'], name='rag_search__chat_id_03c9b1_idx'), models.Index(fields=['message'], name='rag_search__message_b088b6_idx')],
            },
        ),
    ]
