# Generated by Django 5.1.2 on 2026-05-25 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('version', models.CharField(default='1', max_length=50)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('result_schema', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('permission_level', models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('admin', 'Admin'), ('system', 'System')], default='user', max_length=30)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tool_definitions',
                'indexes': [models.Index(fields=['is_enabled', 'permission_level'], name='tool_defini_is_enab_0de8ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_snapshot', models.CharField(max_length=120)),
                ('version_snapshot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], default='requested', max_length=30)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('raw_arguments', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('permission_result', models.JSONField(blank=True, default=dict)),
                ('sequence', models.IntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='chat.chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calls', to='tools.tooldefinition')),
            ],
            options={
                'db_table': 'tool_calls',
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.IntegerField(default=1)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timed_out', 'Timed Out'), ('cancelled', 'Cancelled')], default='running', max_length=30)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('stdout', models.TextField(default='')),
                ('stderr', models.TextField(default='')),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tools.toolcall')),
            ],
            options={
                'db_table': 'tool_executions',
            },
        ),
        migrations.CreateModel(
            name='ToolPermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='tools.tooldefinition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tool_permission_grants',
            },
        ),
        migrations.CreateModel(
            name='ToolResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('artifact', models.CharField(blank=True, max_length=1024, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='tools.toolexecution')),
                ('tool_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tools.toolcall')),
            ],
            options={
                'db_table': 'tool_results',
            },
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['chat', 'sequence'], name='tool_calls_chat_id_c2d9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['user', '-created_at'], name='tool_calls_user_id_e840cc_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['tool', 'status', '-created_at'], name='tool_calls_tool_id_780f64_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['message', 'sequence'], name='tool_calls_message_ff49e3_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['status'], name='tool_calls_status_4c51ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolcall',
            constraint=models.UniqueConstraint(fields=('message', 'sequence'), name='unique_tool_call_sequence'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_call', 'attempt'], name='tool_execut_tool_ca_7e4d60_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['status', '-created_at'], name='tool_execut_status_9f1d78_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.UniqueConstraint(fields=('tool_call', 'attempt'), name='unique_tool_execution_attempt'),
        ),
        migrations.AddIndex(
            model_name='toolpermissiongrant',
            index=models.Index(fields=['tool', 'user'], name='tool_permis_tool_id_136532_idx'),
        ),
        migrations.AddIndex(
            model_name='toolpermissiongrant',
            index=models.Index(fields=['tool', 'role'], name='tool_permis_tool_id_4ca644_idx'),
        ),
        migrations.AddIndex(
            model_name='toolresult',
            index=models.Index(fields=['tool_call'], name='tool_result_tool_ca_ba825a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolresult',
            index=models.Index(fields=['created_at'], name='tool_result_created_146458_idx'),
        ),
    ]
