# Generated by Django 5.1.2 on 2026-05-25 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding'), ('vision_analysis', 'Vision Analysis'), ('compaction', 'Compaction'), ('memory', 'Memory'), ('tool_call', 'Tool Call')], max_length=50)),
                ('provider', models.CharField(default='litellm', max_length=100)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('step_index', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='chat.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='chat.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_usage',
                'indexes': [models.Index(fields=['created_at'], name='token_usage_created_f867dc_idx'), models.Index(fields=['user', '-created_at'], name='token_usage_user_id_972336_idx'), models.Index(fields=['chat', '-created_at'], name='token_usage_chat_id_74ec22_idx'), models.Index(fields=['model'], name='token_usage_model_43a03a_idx'), models.Index(fields=['operation'], name='token_usage_operati_3c3d59_idx')],
            },
        ),
    ]
